before:
  hooks:
    - /bin/sh -c "echo {{.Tag}} > misc/version"

builds:
  - env:
      - CGO_ENABLED=0
    main: ./
    binary: gosmee
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w
      - -s
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: gosmee
    tap:
      owner: chmouel
      name: gosmee
    folder: Formula
    homepage: "https://github.com/chmouel/gosmee"
    description: gosmee  - smee.io go client
    install: |
      bin.install "gosmee" => "gosmee"
      output = Utils.popen_read("SHELL=bash #{bin}/gosmee completion bash")
      (bash_completion/"gosmee").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion zsh")
      (zsh_completion/"_gosmee").write output
      prefix.install_metafiles

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  prerelease: false

nfpms:
  - file_name_template: "gosmee-{{.Version}}_{{.Os}}-{{.Arch}}"
    homepage: https://github.com/chmouel/gosmee
    description: "Gosmee - smee.io forwarder in go"
    maintainer: Chmouel Boudjnah <chmouel@chmouel.com>
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Brew formula update"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - Update README.md

universal_binaries:
  - replace: true
    name_template: "gosmee"

aurs:
  - name: gosmee-bin
    homepage: "https://github.com/chmouel/gosmee"
    description: "Gosmee - smee.io forwarder in go"
    maintainers:
      - "Chmouel Boudjnah <chmouel@chmouel.com>"
    license: Apache 2.0
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/gosmee-bin.git
    package: |-
      # bin
      install -Dm755 "./gosmee" "${pkgdir}/usr/bin/gosmee"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/gosmee/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"

      ./gosmee completion zsh > gosmee.zsh
      ./gosmee completion bash > gosmee.bash

      install -Dm644 "gosmee.bash" "${pkgdir}/usr/share/bash-completion/completions/gosmee"
      install -Dm644 "gosmee.zsh" "${pkgdir}/usr/share/zsh/site-functions/_gosmee"
