before:
  hooks:
    - /bin/sh -c "printf {{.Version }} > gosmee/templates/version"

builds:
  - env:
      - CGO_ENABLED=0
    main: ./
    binary: gosmee
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - s390x
      - ppc64le
    ldflags:
      - -w
      - -s
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: gosmee
    tap:
      owner: chmouel
      name: gosmee
    folder: Formula
    homepage: "https://github.com/chmouel/gosmee"
    description: "gosmee - A webhook and https://smee.io forwarder"
    install: |
      output = Utils.popen_read("SHELL=bash #{bin}/gosmee completion bash")
      (bash_completion/"gosmee").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion zsh")
      (zsh_completion/"_gosmee").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion fish")
      (fish_completion/"gosmee.fish").write output
      prefix.install_metafiles
checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  prerelease: "false"

nfpms:
  - file_name_template: "gosmee-{{.Version}}_{{.Os}}-{{.Arch}}"
    homepage: https://github.com/chmouel/gosmee
    description: "gosmee - A webhook and https://smee.io forwarder"
    maintainer: Chmouel Boudjnah <chmouel@chmouel.com>
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
    contents:
      - src: ./misc/gosmee-server.service
        dst: /etc/systemd/system/gosmee-server.service
        type: "config|noreplace"
      - src: ./misc/gosmee.service
        dst: /etc/systemd/system/gosmee-client.service
        type: "config|noreplace"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Brew formula update"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - Update README.md

universal_binaries:
  - replace: true
    name_template: "gosmee"

aurs:
  - name: gosmee-bin
    homepage: "https://github.com/chmouel/gosmee"
    description: "gosmee - A webhook and https://smee.io forwarder"
    maintainers:
      - "Chmouel Boudjnah <chmouel@chmouel.com>"
    license: Apache 2.0
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/gosmee-bin.git
    package: |-
      # bin
      install -Dm755 "./gosmee" "${pkgdir}/usr/bin/gosmee"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/gosmee/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"

      for i in zsh bash fish;do
        ./gosmee completion ${i} > gosmee.${i}
      done

      install -Dm644 "gosmee.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/gosmee"
      install -Dm644 "gosmee.bash" "${pkgdir}/usr/share/bash-completion/completions/gosmee"
      install -Dm644 "gosmee.zsh" "${pkgdir}/usr/share/zsh/site-functions/_gosmee"
