# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosmee < Formula
  desc "gosmee - A webhook and https://smee.io forwarder"
  homepage "https://github.com/chmouel/gosmee"
  version "0.29.0"

  on_macos do
    url "https://github.com/chmouel/gosmee/releases/download/v0.29.0/gosmee_0.29.0_darwin_all.tar.gz"
    sha256 "07ae66eaf473d12c5b9e93f7741bc2fa403f53a483146a18ea5ef1aefa0b573f"

    def install
      bin.install "gosmee" => "gosmee"
      output = Utils.popen_read("SHELL=bash #{bin}/gosmee completion bash")
      (bash_completion/"gosmee").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion zsh")
      (zsh_completion/"_gosmee").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion fish")
      (fish_completion/"gosmee.fish").write output
      prefix.install_metafiles
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chmouel/gosmee/releases/download/v0.29.0/gosmee_0.29.0_linux_x86_64.tar.gz"
      sha256 "9f0cddee4ef2821aca2e07c5e5beb92ff8c1c0576d3d423be72c13dfc7dedb8b"
      def install
        bin.install "gosmee" => "gosmee"
        output = Utils.popen_read("SHELL=bash #{bin}/gosmee completion bash")
        (bash_completion/"gosmee").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion zsh")
        (zsh_completion/"_gosmee").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion fish")
        (fish_completion/"gosmee.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chmouel/gosmee/releases/download/v0.29.0/gosmee_0.29.0_linux_arm64.tar.gz"
      sha256 "a9cd08947101d4741310c4c5589d16f818b10d69686ab5f36babd959305570f5"
      def install
        bin.install "gosmee" => "gosmee"
        output = Utils.popen_read("SHELL=bash #{bin}/gosmee completion bash")
        (bash_completion/"gosmee").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion zsh")
        (zsh_completion/"_gosmee").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion fish")
        (fish_completion/"gosmee.fish").write output
        prefix.install_metafiles
      end
    end
  end
end
