# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosmee < Formula
  desc "gosmee - A webhook and https://smee.io forwarder"
  homepage "https://github.com/chmouel/gosmee"
  version "0.18.0"

  on_macos do
    url "https://github.com/chmouel/gosmee/releases/download/0.18.0/gosmee_0.18.0_MacOS_all.tar.gz"
    sha256 "92108b9202711d75f008d489f376bce0ffd504d7577667f72a0965d8565a2c99"

    def install
      output = Utils.popen_read("SHELL=bash #{bin}/gosmee completion bash")
      (bash_completion/"gosmee").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion zsh")
      (zsh_completion/"_gosmee").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion fish")
      (fish_completion/"gosmee.fish").write output
      prefix.install_metafiles
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chmouel/gosmee/releases/download/0.18.0/gosmee_0.18.0_Linux_x86_64.tar.gz"
      sha256 "e7575a959df435906464ac6e32d40286e65e5d29ee313fcbc37fc3674e713c08"

      def install
        output = Utils.popen_read("SHELL=bash #{bin}/gosmee completion bash")
        (bash_completion/"gosmee").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion zsh")
        (zsh_completion/"_gosmee").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion fish")
        (fish_completion/"gosmee.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chmouel/gosmee/releases/download/0.18.0/gosmee_0.18.0_Linux_arm64.tar.gz"
      sha256 "62b6960fcca3fab3e77d034394b4fba647e3da7731754a8f9bce30728da28c7e"

      def install
        output = Utils.popen_read("SHELL=bash #{bin}/gosmee completion bash")
        (bash_completion/"gosmee").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion zsh")
        (zsh_completion/"_gosmee").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion fish")
        (fish_completion/"gosmee.fish").write output
        prefix.install_metafiles
      end
    end
  end
end
