# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosmee < Formula
  desc "gosmee - A webhook and https://smee.io forwarder"
  homepage "https://github.com/chmouel/gosmee"
  version "0.23.3"

  on_macos do
    url "https://github.com/chmouel/gosmee/releases/download/v0.23.3/gosmee_0.23.3_darwin_all.tar.gz"
    sha256 "d109697c1e18a035901f2fb61a54948be162f0a4c4d850f8afc15d1340cba0d2"

    def install
      bin.install "gosmee" => "gosmee"
      output = Utils.popen_read("SHELL=bash #{bin}/gosmee completion bash")
      (bash_completion/"gosmee").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion zsh")
      (zsh_completion/"_gosmee").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion fish")
      (fish_completion/"gosmee.fish").write output
      prefix.install_metafiles
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chmouel/gosmee/releases/download/v0.23.3/gosmee_0.23.3_linux_x86_64.tar.gz"
        sha256 "9a0a3382a153bef642739d7d4f07b7bd7a845d54dbd5b9e647f0e3c601d14d9e"

        def install
          bin.install "gosmee" => "gosmee"
          output = Utils.popen_read("SHELL=bash #{bin}/gosmee completion bash")
          (bash_completion/"gosmee").write output
          output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion zsh")
          (zsh_completion/"_gosmee").write output
          output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion fish")
          (fish_completion/"gosmee.fish").write output
          prefix.install_metafiles
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chmouel/gosmee/releases/download/v0.23.3/gosmee_0.23.3_linux_arm64.tar.gz"
        sha256 "0eafc8c97b2cf8850aeeb26e0fb3852a4b76d8e9b4191dac82997b9a7905c1d2"

        def install
          bin.install "gosmee" => "gosmee"
          output = Utils.popen_read("SHELL=bash #{bin}/gosmee completion bash")
          (bash_completion/"gosmee").write output
          output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion zsh")
          (zsh_completion/"_gosmee").write output
          output = Utils.popen_read("SHELL=zsh #{bin}/gosmee completion fish")
          (fish_completion/"gosmee.fish").write output
          prefix.install_metafiles
        end
      end
    end
  end
end
