{{- if (include "gosmee.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gosmee.fullname" . }}
  labels:
    {{- include "gosmee.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.server.secret.webhookSignatures }}
  GOSMEE_WEBHOOK_SIGNATURE: {{ join "," . | quote }}
  {{- end }}
  {{- with .Values.server.secret.replayToken }}
  GOSMEE_REPLAY_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.server.redis.url }}
  GOSMEE_REDIS_URL: {{ . | quote }}
  {{- end }}
{{- end }}
