{{- if and .Values.server.encryptedChannels.enabled (not .Values.server.encryptedChannels.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gosmee.encryptedChannelsSecretName" . }}
  labels:
    {{- include "gosmee.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.server.encryptedChannels.key }}: |
    {{- dict "channels" .Values.server.encryptedChannels.channels | toPrettyJson | nindent 4 }}
{{- end }}
